### ISSUE TITLE
No response at all by using the given example

### ISSUE THREAD

**Issue by herzphi** [enjoyneering/AHTxx#13]
I am using a WeMos D1 Mini with a AHT10.
The connections are from the AHT10 to WeMos:

SDA -> D2 (GPIO4)
SCL -> D1 (GPIO5)
VIN -> 3V3
GND -> G

Adress pin is 0x38.

After flashing with your example I get the error checking for the wiring, but it seems correct to me.

**Comment by enjoyneering** [comment]
please provide the picture of your AHT10.

**Comment by herzphi** [comment]
It seemed a be defect Wemos, so it works all fine.
