### ISSUE TITLE
Suggested small optimization

### ISSUE THREAD

**Issue by neutralvibes** [enjoyneering/AHTxx#16]
This isn't a fault as your library is already wonderful, however, I was wondering if there was a reason for multiple `Wire` reads to grab the raw data, as in:

~~~c++
  /* read n-bytes from "wire.h" rxBuffer */
for (uint8_t i = 0; i < dataSize; i++)
{
   _rawData[i] = Wire.read(); 
 }
 ~~~
 
Tested only on the esp8266, the following appears to do the same without issue
~~~c++
  Wire.readBytes(_rawData, dataSize);
~~~

Sorry if I have wasted your time, but thought this may be useful to eliminate 6-7 reads. .

**Comment by enjoyneering** [comment]
Good catch. Thank you. Library updated.
