### ISSUE TITLE
AHTxx.cpp:101:8: error: 'class TwoWire' has no member named 'setClockStretchLimit'

### ISSUE THREAD

**Issue by gotfredsen** [enjoyneering/AHTxx#2]
I get this:

```
/Users/.../Documents/Arduino/libraries/AHTxx/src/AHTxx.cpp:101:8: error: 'class TwoWire' has no member named 'setClockStretchLimit'
   Wire.setClockStretchLimit(stretch); //experimental! default 150000usec
        ^~~~~~~~~~~~~~~~~~~~
```
so I commented out the line and now it works.

My Arduino installation is brand new, with latest libraries, on a new Mac. I used to use AHT10, but this pointed me to this library, so I haven't used it before. Running on a ESP32.

**Comment by davidkleng** [comment]
Hi, im using ATMEGA328 with MiniCore and have the same problem. 
My solution was to simply go to AHTxx.cpp, line 91 and changed the following:

`
  // Wire.setWireTimeout(stretch, false); //experimental! default 25000usec, true-Wire hardware will be automatically reset on timeout
  Wire.setTimeout(stretch);
`

**Comment by enjoyneering** [comment]
Hi folks,

Thank you for feedback. You probably need to update Arduino AVR Core. Recently Wire.setWireTimeout timeout API methods were added to the AVR Wire library. See https://github.com/arduino/Arduino/issues/10803

**Comment by gotfredsen** [comment]
> Hi folks,
> 
> Thank you for feedback. You probably need to update Arduino AVR Core. Recently Wire.setWireTimeout() timeout API method was added to the AVR Wire library. See [arduino/Arduino#10803](https://github.com/arduino/Arduino/issues/10803)

I am using an ESP32, not an AVR Core, and both Arduino and ESP32 board files were installed same day. Maybe the changes you are referring to has not yet been implemented for the ESP cores.

**Comment by enjoyneering** [comment]
Hi gotfredsen,

You're right. For some reason, Arduino ESP32 uses Wire.setTimeout(stretch) in milliseconds, while Arduino ESP8266 uses setClockStretchLimit(uint32_t) in microseconds. I believe the timeout for the I2C bus in milliseconds is too long, so in the library the timeout is in microseconds.

The library has been updated.

**Comment by enjoyneering** [comment]
fixed, see https://github.com/enjoyneering/AHTxx/issues/5
