### ISSUE TITLE
Использование сенсора AHT10 одновременно с дисплеем Nokia5110 на шине I2C

### ISSUE THREAD

**Issue by brightproject** [enjoyneering/AHTxx#4]
Шина I2C(SDA, SDL) позволяет подключать несколько датчиков.
Но позволяет она подключать дисплей нокия 5110?
Как то эта библиотека позволяет решить проблему.
Получаю при подключении дисплея на шину I2C значения 255.

**Comment by enjoyneering** [comment]
насколько мне известно дисплей от Nokia5110 построен на базе PCD8544, а это SPI и к I2C никакого отношения не имеет.
