### ISSUE TITLE
ESP01s not working with library

### ISSUE THREAD

**Issue by Avpi18** [enjoyneering/AHTxx#6]
With the Wemos D1 mini, the library works wonderfully and without errors. However, when I try to run the example code from the AHT2x on an ESP01s, I always get the same error: "AHT2x not connected or fail to load calibration ... ".

How can I get the code to run?

**Comment by enjoyneering** [comment]
It is working. I use it every day in my tthRelay project.

For ESP-01 you need set up SDA& SCK pin

`aht10.begin(0, 2, 400000); //sda, scl, speed in Hz`

**Comment by Avpi18** [comment]
Many thanks
From the newbie 👍🏻😊
